version: '3.7'
services: 
    pihole:
        container_name: pihole
        image: pihole/pihole
        ports:
            - "53:53/udp"
            - "53:53/tcp"
            - "67:67/tcp"
            - "80:80/tcp"
            - "443:443/tcp"
        environment: 
            TZ: "Asia/Bangkok"
            WEBPASSWORD: "P@ssw0rd"
        volumes:
            - './etc/pihole/:/etc/pihole/'
            - './etc-dnsmaq.d/:/etc/etc-dnsmaq.d/'
        dns:
            - 1.1.1.1
            - 127.0.0.1
        cap_add: 
            - NET_ADMIN 
        restart:  unless-stopped